import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/About.module.css'
import missionSprout from '@/public/logos/ourMission.svg'
import solutionSprout from '@/public/logos/ourSolution.svg'
import Navbar from '@/components/Navbar'
import Navid from '@/components/Navid'
import Thamasha from '@/components/Thamasha'
import Lauryn from '@/components/Lauryn'
import VeganDish1 from '@/public/pictures/vegan-Pho.jpeg'
import VeganDish2 from '@/public/pictures/vegan-salad.jpeg'

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.container}>
          

          <h1 className={styles.header}>About Us</h1>

          <h2 className={styles.missionSubhead}>Our Mission</h2>

          <section className={styles.missionSprout}>
            <Image src={missionSprout} width={200} height={300}/>
          </section>

          <section className={styles.mission}>
            <p className={styles.ourMission}>
              Here at Plantifull Recipes our goal is to help support and grow the Vegan and Vegetarian community. We believe in not only helping the planet but eating healthier in a funny and tasty manner! We hope that we can help encourage curious eaters to try our vegan and vegetarian recipes and break the stigma that plant based meals aren’t delicious or can’t make for a filling meal. 
            </p>

            <p className={styles.ourMission}>
              By cutting down on the amount of meat product we consume, we can also save millions of animals from being slaughtered every year in unethically practiced slaughter houses and farms.
            </p>

            <h2 className={styles.solutionSubhead}>Our Solution</h2>

            <section className={styles.solutionSprout}>
              <Image src={solutionSprout} width={250} height={350}/>
            </section>

            <p className={styles.ourSolution1}>
              When we asked ourselves what was stopping people from converting vegan or vegetarian diets, we found that a lot of people had misconceptions about vegan and vegetarianism. One of them being that, Vegan and Vegetarian food is limited in cuisine variety. 
            </p>

            <p className={styles.ourSolution1}>
              This is incorrect, and in order to prove that Vegan and Vegetarian dishes span a wide variety of cuisines, we researched recipes from around the world including from East Asia, South Asia, Europe and North America so that anyone can enjoy a recipe that suits their taste. 
            </p>

            <div className={styles.foodImages}>
              <Image src={VeganDish1} width={160} height={160}/>
              <Image src={VeganDish2} width={160} height={160}/>
            </div>

          </section>
          
     
          <p className={styles.ourSolution2}>
            The second other reason why people are reluctant to switch is due to them missing meat. This is not a problem! We know the transition from meat to a completely plant based diet isn’t an easy one and that not everyone has the same dietary needs.
          </p>

          <p className={styles.ourSolution2}>
            So we’ve included a wide range of recipes that cater to sub-groups of Vegetarianism including, Pescatarians, Ovo-Vegetarians and Lacto-Ovo-Vegetarians. We want to be inclusive to all subcategories of Vegetarianism and don’t want to shame anyone for their dietary needs.
          </p>

          <h1 className={styles.ourTeam}>Our Team</h1>

          <div className={styles.teamCards}>
            <Navid/>
          </div>

          <div className={styles.teamCards}>
            <Thamasha/>
          </div>
         
          <div className={styles.teamCards}>
            <Lauryn/>
          </div>

        </div>

      </main>
    </>
  )
}

