import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/CallToAction.module.css'
import Navbar from '@/components/Navbar'

export default function CallToAction() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.container}>
         
            <h1 className={styles.callToAction}>Call To Action</h1>

            <section className={styles.happeningRightNow}>

              <h2 className={styles.sectionheader}>What's Happening Right Now</h2>

              <p className={styles.bodyCopy}>
                For years now Global Warming has been the current cause of concern for many people and has only been on the rise since then. Due to the effects of global warming and greenhouse gasses, we’ve started to see many environmental effects on our planet every year, including melting glaciers, rising water levels and extreme weather shifts. 
              </p>
            </section>

            <section className={styles.globalWarming}>
              <h2 className={styles.sectionheader}>What is Global Warming?</h2>

              <p className={styles.bodyCopy}>
                But what is exactly global warming and what causes it? Global Warming is the naturally occurring phenomena in which the earth experiences temperature fluctuations over the course of millions of years. These temperature fluctuations are caused by the greenhouse gas emissions that are released into earth’s atmosphere. However, due to industrial factories and other related practices the rate at which the earth is experiencing global warming is rapidly increasing. As a result, we are now seeing the effects of global warming both on us and our environment. 
              </p>
            </section>

            <section className={styles.meatIndustry}>
              <h2 className={styles.sectionheader}>How Does Eating Meat Contribute To Global Warming?</h2>

              <p className={styles.bodyCopy}>
                The meat industry is a prime factor for the increase in global warming due to the sheer amount of resources needed for the agricultural industry. Every year countless forests and landscapes are bulldozed and developed to create more room for ever expanding factories and farms. However, it’s not only the factories that contribute to CO2 emissions but the animals themselves, and with the increasing demand for more meat this creates a larger impact on both the environment and animals
              </p>

              <p className={styles.bodyCopy}>
                According to WorldAnimalProtection.ca the consumption of animal products processed in factories and farms contributes to 45% of agricultural greenhouse gas emissions. Due to the rising demand of meat, companies have since increased the amount of livestock to meet consumer demands. Unfortunately, this comes at the cost of both the environment and the well-being and treatment of the animals. 
              </p>
            </section>

            <section>
              <h2 className={styles.sectionheader}>What Can We Do About This</h2>

              <p className={styles.bodyCopy}>
              The answer? Eat less meat. By lowering the demand of meat and meat by-products we can reduce the need for agricultural factories. This also includes animal farms, slaughterhouses, meat processing factories and animal food crop farms. 
              </p>

              <p className={styles.bodyCopy}>
              Anothering thing that we can do to help stop global warming is to buy from local and organic grocery stores. Emissions are also created from transporting farm products to and from farms to factories to super markets. The less farther the sources, the fewer greenhouse gasses are created. Although unstandably organic isn’t cheap, an alternative solution is to try cutting down on grocery costs by growing simple plants yourself! Growing food doesn’t mean you need a lot of land. Try planting cherry tomatoes on your balcony or green onion from your window sill. There are many creative and small ways we can take part in helping our planet, and it all starts with going green.
              </p>
            </section>
        </div>
      </main>
    </>
  )
}
