import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import BeginBox from '@/components/BeginBox'
import  Sprout  from '@/public/logos/Logo_no-bkg.svg'
import Navbar from '@/components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <section className={styles.logoSection}>
          <Image className={styles.sprout} src={Sprout} width={250} height={300} />
        </section>
        <BeginBox/>
      </main>
    </>
  )
} 