import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Landing.module.css'

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Welcome to Plantifull Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         
      </main>
    </>
  )
} 