import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Quiz.module.css'
import QuestionBoxOne from '@/components/QuestionBoxOne'
import QuestionBoxTwo from '@/components/QuestionBoxTwo'
import QuestionBoxThree from '@/components/QuestionBoxThree'

export default function Quiz() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.questionCont}>
          <QuestionBoxThree />
        </div>
        <div className={styles.questionCont}>
          <QuestionBoxTwo />
        </div>
        <div className={styles.questionCont}>
          <QuestionBoxOne />
        </div>
      </main>
    </>
  )
}
