import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Story.module.css'
import DialogueBox from '@/components/DialogueBox'
import StoryCarousel from '@/components/storyCarousel'
import NavbarHollow from '@/components/NavbarHollow'

export default function Story() {
  return (
    <>
      <Head>
        <title>Sprout's Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavbarHollow />
        <StoryCarousel />
      </main>
    </>
  )
}