import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Tutorial.module.css'

export default function Tutorial() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          <Image className={styles.tutimg1} src="/tutimg1" width={200} height={200}/>
        <Image className={styles.tutimg2} src={tutimg2} width={100} height={100} />
        <Image className={styles.tutimg3} src={tutimg3} width={100} height={100} /> */}
        </section>
      </main>
    </>
  )
}
